; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_strncmpi_a
PUBLIC	_strncmpi_w
; Function compile flags: /Ogspy
;	COMDAT _strncmpi_w
_TEXT	SEGMENT
s1$ = 8
s2$ = 16
cchars$ = 24
_strncmpi_w PROC					; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 34
	cmp	rcx, rdx
	je	SHORT $LN25@strncmpi_w
; Line 37
	test	rcx, rcx
	jne	SHORT $LN6@strncmpi_w
; Line 38
	or	eax, -1
; Line 55
	ret	0
$LN6@strncmpi_w:
; Line 40
	test	rdx, rdx
	jne	SHORT $LN7@strncmpi_w
; Line 41
	lea	eax, QWORD PTR [rdx+1]
; Line 55
	ret	0
$LN7@strncmpi_w:
; Line 43
	test	r8, r8
	je	SHORT $LN25@strncmpi_w
	sub	rcx, rdx
$LL4@strncmpi_w:
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	movzx	eax, WORD PTR [rcx+rdx]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 48
	movzx	r9d, WORD PTR [rcx+rdx]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	sub	ax, 65					; 00000041H
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 50
	movzx	r10d, WORD PTR [rdx]
	add	r9w, 32					; 00000020H
	cmp	ax, 25
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	movzx	eax, WORD PTR [rdx]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 48
	cmova	r9w, WORD PTR [rcx+rdx]
; Line 50
	add	r10w, 32				; 00000020H
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	sub	ax, 65					; 00000041H
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 50
	cmp	ax, 25
	cmova	r10w, WORD PTR [rdx]
; Line 51
	dec	r8
	lea	rdx, QWORD PTR [rdx+2]
; Line 52
	test	r9w, r9w
	je	SHORT $LN9@strncmpi_w
	cmp	r9w, r10w
	jne	SHORT $LN9@strncmpi_w
	test	r8, r8
	jne	SHORT $LL4@strncmpi_w
$LN9@strncmpi_w:
; Line 54
	movzx	ecx, r10w
	movzx	eax, r9w
	sub	eax, ecx
; Line 55
	ret	0
$LN25@strncmpi_w:
; Line 44
	xor	eax, eax
; Line 55
	ret	0
_strncmpi_w ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _strncmpi_a
_TEXT	SEGMENT
s1$ = 8
s2$ = 16
cchars$ = 24
_strncmpi_a PROC					; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 4
	mov	r10, rdx
	mov	r9, rcx
; Line 7
	cmp	rcx, rdx
	je	SHORT $LN25@strncmpi_a
; Line 10
	test	rcx, rcx
	jne	SHORT $LN6@strncmpi_a
; Line 11
	or	eax, -1
; Line 28
	ret	0
$LN6@strncmpi_a:
; Line 13
	test	rdx, rdx
	jne	SHORT $LN7@strncmpi_a
; Line 14
	lea	eax, QWORD PTR [rdx+1]
; Line 28
	ret	0
$LN7@strncmpi_a:
; Line 16
	test	r8, r8
	je	SHORT $LN25@strncmpi_a
	sub	r9, rdx
$LL4@strncmpi_a:
; Line 20
	movzx	edx, BYTE PTR [r9+r10]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 17
	lea	ecx, DWORD PTR [rdx-65]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 21
	cmp	cl, 25
	lea	eax, DWORD PTR [rdx+32]
	movzx	r11d, al
	cmova	r11d, edx
	movzx	edx, BYTE PTR [r10]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 17
	lea	ecx, DWORD PTR [rdx-65]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strncmpi.c
; Line 23
	cmp	cl, 25
	lea	eax, DWORD PTR [rdx+32]
	cmova	eax, edx
	inc	r10
; Line 24
	dec	r8
; Line 25
	test	r11b, r11b
	je	SHORT $LN9@strncmpi_a
	cmp	r11b, al
	jne	SHORT $LN9@strncmpi_a
	test	r8, r8
	jne	SHORT $LL4@strncmpi_a
$LN9@strncmpi_a:
; Line 27
	movsx	ecx, al
	movsx	eax, r11b
	sub	eax, ecx
; Line 28
	ret	0
$LN25@strncmpi_a:
; Line 17
	xor	eax, eax
; Line 28
	ret	0
_strncmpi_a ENDP
_TEXT	ENDS
END
