; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_strcmpi_a
PUBLIC	_strcmpi_w
; Function compile flags: /Ogspy
;	COMDAT _strcmpi_w
_TEXT	SEGMENT
s1$ = 8
s2$ = 16
_strcmpi_w PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 30
	cmp	rcx, rdx
	jne	SHORT $LN5@strcmpi_w
; Line 31
	xor	eax, eax
; Line 47
	ret	0
$LN5@strcmpi_w:
; Line 33
	test	rcx, rcx
	jne	SHORT $LN6@strcmpi_w
; Line 34
	or	eax, -1
; Line 47
	ret	0
$LN6@strcmpi_w:
; Line 36
	test	rdx, rdx
	jne	SHORT $LN23@strcmpi_w
; Line 37
	lea	eax, QWORD PTR [rdx+1]
; Line 47
	ret	0
$LN23@strcmpi_w:
	sub	rcx, rdx
$LL4@strcmpi_w:
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	movzx	eax, WORD PTR [rcx+rdx]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 41
	movzx	r8d, WORD PTR [rcx+rdx]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	sub	ax, 65					; 00000041H
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 43
	movzx	r9d, WORD PTR [rdx]
	add	r8w, 32					; 00000020H
	cmp	ax, 25
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	movzx	eax, WORD PTR [rdx]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 41
	cmova	r8w, WORD PTR [rcx+rdx]
; Line 43
	add	r9w, 32					; 00000020H
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 25
	sub	ax, 65					; 00000041H
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 43
	cmp	ax, 25
	cmova	r9w, WORD PTR [rdx]
	lea	rdx, QWORD PTR [rdx+2]
; Line 44
	test	r8w, r8w
	je	SHORT $LN8@strcmpi_w
	cmp	r8w, r9w
	je	SHORT $LL4@strcmpi_w
$LN8@strcmpi_w:
; Line 46
	movzx	ecx, r9w
	movzx	eax, r8w
	sub	eax, ecx
; Line 47
	ret	0
_strcmpi_w ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _strcmpi_a
_TEXT	SEGMENT
s1$ = 8
s2$ = 16
_strcmpi_a PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 4
	mov	r9, rdx
	mov	r8, rcx
; Line 7
	cmp	rcx, rdx
	jne	SHORT $LN5@strcmpi_a
; Line 8
	xor	eax, eax
; Line 24
	ret	0
$LN5@strcmpi_a:
; Line 10
	test	r8, r8
	jne	SHORT $LN6@strcmpi_a
; Line 11
	or	eax, -1
; Line 24
	ret	0
$LN6@strcmpi_a:
; Line 13
	test	rdx, rdx
	jne	SHORT $LN23@strcmpi_a
; Line 14
	lea	eax, QWORD PTR [rdx+1]
; Line 24
	ret	0
$LN23@strcmpi_a:
	sub	r8, rdx
$LL4@strcmpi_a:
; Line 17
	movzx	edx, BYTE PTR [r8+r9]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 17
	lea	ecx, DWORD PTR [rdx-65]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 18
	cmp	cl, 25
	lea	eax, DWORD PTR [rdx+32]
	movzx	r10d, al
	cmova	r10d, edx
	movzx	edx, BYTE PTR [r9]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\rtltypes.h
; Line 17
	lea	ecx, DWORD PTR [rdx-65]
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcmpi.c
; Line 20
	cmp	cl, 25
	lea	eax, DWORD PTR [rdx+32]
	movzx	r11d, al
	cmova	r11d, edx
	inc	r9
; Line 21
	test	r10b, r10b
	je	SHORT $LN8@strcmpi_a
	cmp	r10b, r11b
	je	SHORT $LL4@strcmpi_a
$LN8@strcmpi_a:
; Line 23
	movsx	ecx, r11b
	movsx	eax, r10b
	sub	eax, ecx
; Line 24
	ret	0
_strcmpi_a ENDP
_TEXT	ENDS
END
