; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_strcat_a
PUBLIC	_strcat_w
; Function compile flags: /Ogspy
;	COMDAT _strcat_w
_TEXT	SEGMENT
dest$ = 8
src$ = 16
_strcat_w PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcat.c
; Line 23
	xor	r8d, r8d
	test	rcx, rcx
	je	SHORT $LN7@strcat_w
	test	rdx, rdx
	je	SHORT $LN7@strcat_w
	jmp	SHORT $LN17@strcat_w
$LL2@strcat_w:
; Line 27
	add	rcx, 2
$LN17@strcat_w:
; Line 26
	cmp	WORD PTR [rcx], r8w
	jne	SHORT $LL2@strcat_w
; Line 29
	movzx	eax, WORD PTR [rdx]
	test	ax, ax
	je	SHORT $LN5@strcat_w
	sub	rdx, rcx
$LL4@strcat_w:
; Line 30
	mov	WORD PTR [rcx], ax
; Line 31
	add	rcx, 2
	movzx	eax, WORD PTR [rdx+rcx]
	test	ax, ax
	jne	SHORT $LL4@strcat_w
$LN5@strcat_w:
; Line 35
	mov	WORD PTR [rcx], r8w
$LN7@strcat_w:
; Line 37
	mov	rax, rcx
	ret	0
_strcat_w ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _strcat_a
_TEXT	SEGMENT
dest$ = 8
src$ = 16
_strcat_a PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strcat.c
; Line 5
	xor	r8d, r8d
	test	rcx, rcx
	je	SHORT $LN7@strcat_a
	test	rdx, rdx
	je	SHORT $LN7@strcat_a
	jmp	SHORT $LN17@strcat_a
$LL2@strcat_a:
; Line 9
	inc	rcx
$LN17@strcat_a:
; Line 8
	cmp	BYTE PTR [rcx], r8b
	jne	SHORT $LL2@strcat_a
; Line 11
	mov	al, BYTE PTR [rdx]
	test	al, al
	je	SHORT $LN5@strcat_a
	sub	rdx, rcx
$LL4@strcat_a:
; Line 12
	mov	BYTE PTR [rcx], al
; Line 13
	inc	rcx
	mov	al, BYTE PTR [rdx+rcx]
	test	al, al
	jne	SHORT $LL4@strcat_a
$LN5@strcat_a:
; Line 17
	mov	BYTE PTR [rcx], r8b
$LN7@strcat_a:
; Line 19
	mov	rax, rcx
	ret	0
_strcat_a ENDP
_TEXT	ENDS
END
