; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_strend_a
PUBLIC	_strend_w
; Function compile flags: /Ogspy
;	COMDAT _strend_w
_TEXT	SEGMENT
s$ = 8
_strend_w PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strend.c
; Line 16
	xor	eax, eax
	test	rcx, rcx
	je	SHORT $LN1@strend_w
	jmp	SHORT $LN10@strend_w
$LL2@strend_w:
; Line 20
	add	rcx, 2
$LN10@strend_w:
; Line 19
	cmp	WORD PTR [rcx], ax
	jne	SHORT $LL2@strend_w
; Line 22
	mov	rax, rcx
$LN1@strend_w:
; Line 23
	ret	0
_strend_w ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _strend_a
_TEXT	SEGMENT
s$ = 8
_strend_a PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strend.c
; Line 5
	test	rcx, rcx
	jne	SHORT $LN10@strend_a
; Line 6
	xor	eax, eax
; Line 12
	ret	0
$LL2@strend_a:
; Line 9
	inc	rcx
$LN10@strend_a:
; Line 8
	cmp	BYTE PTR [rcx], 0
	jne	SHORT $LL2@strend_a
; Line 11
	mov	rax, rcx
; Line 12
	ret	0
_strend_a ENDP
_TEXT	ENDS
END
