; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_strlen_a
PUBLIC	_strlen_w
; Function compile flags: /Ogspy
;	COMDAT _strlen_w
_TEXT	SEGMENT
s$ = 8
_strlen_w PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strlen.c
; Line 20
	xor	edx, edx
	mov	rax, rcx
	test	rcx, rcx
	jne	SHORT $LN10@strlen_w
; Line 27
	ret	0
$LL2@strlen_w:
; Line 24
	add	rcx, 2
$LN10@strlen_w:
; Line 23
	cmp	WORD PTR [rcx], dx
	jne	SHORT $LL2@strlen_w
; Line 26
	sub	rcx, rax
	sar	rcx, 1
	mov	rax, rcx
; Line 27
	ret	0
_strlen_w ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _strlen_a
_TEXT	SEGMENT
s$ = 8
_strlen_a PROC						; COMDAT
; File C:\Users\Majdev\Desktop\Furutaka\minirtl\_strlen.c
; Line 5
	mov	rax, rcx
; Line 7
	test	rcx, rcx
	jne	SHORT $LN10@strlen_a
; Line 14
	ret	0
$LL2@strlen_a:
; Line 11
	inc	rcx
$LN10@strlen_a:
; Line 10
	cmp	BYTE PTR [rcx], 0
	jne	SHORT $LL2@strlen_a
; Line 13
	sub	rcx, rax
	mov	rax, rcx
; Line 14
	ret	0
_strlen_a ENDP
_TEXT	ENDS
END
